Rule out `uv` dependency management issue

* if we can use this image and read in geojson, with token, then it is dependency issue

In [1]:
import geopandas as gpd
import google.auth

from ridership_utils import utils
credentials, project = google.auth.default()
GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/transit-ridership-analytics/"
INTERMED_GCS = f"{GCS_FILE_PATH}intermediate/"
PROCESSED_GCS = f"{GCS_FILE_PATH}processed/"
PUBLIC_GCS = "gs://calitp-publish-data-analysis/"
SHARED_GCS = "gs://calitp-analytics-data/data-analyses/shared_data/"

In [8]:
roads = gpd.read_parquet(
    f"{SHARED_GCS}public_road_functional_classification.parquet",
    storage_options={"token": credentials.token}
)

In [9]:
utils.geojson_gcs_export(
    roads,
    SHARED_GCS, 
    "test_roads"
)

In [10]:
roads_df = utils.read_geojson(
    f"{SHARED_GCS}",
    "test_roads",
)

In [11]:
roads.shape, roads_df.shape

((779834, 8), (779834, 8))

In [12]:
roads.head(2)

,OBJECTID,EventID,RouteID,F_System,Shape__Length,County_label,Caltrans_District,geometry
0,1,900078,SHS_009._P,4,372.219375,SANTA CRUZ,5,"MULTILINESTRING ((-122.14576 37.19587, -122.14..."
1,2,900081,SHS_009._P,3,5207.569145,SANTA CLARA,4,"MULTILINESTRING ((-122.02759 37.25511, -122.02..."

In [13]:
roads_df.head(2)

,OBJECTID,EventID,RouteID,F_System,Shape__Length,County_label,Caltrans_District,geometry
0,1,900078,SHS_009._P,4,372.219375,SANTA CRUZ,5,"MULTILINESTRING ((-122.14576 37.19587, -122.14..."
1,2,900081,SHS_009._P,3,5207.569145,SANTA CLARA,4,"MULTILINESTRING ((-122.02759 37.25511, -122.02..."

In [ ]:
# Read in test files, this is the geoparquet
gdf = gpd.read_parquet(
    f"{INTERMED_GCS}dim_stops_with_feed_service_period.parquet",
    storage_options={"token": credentials.token}
)

In [3]:
# test.geojson is the same as dim_stops_with_feed_service
df = utils.read_geojson(
    f"{PROCESSED_GCS}publish/",
    "test",
)

In [4]:
df

,key,feed_key,stop_id,stop_name,stop_code,schedule_name,service_date_start,service_date_end,geometry
0,5e9351614aba649b95b6d6bc4bcc95c5,f88919081c15e52e44adaf0ba48e6dbc,95,Hwy 111 at Arabia,95,SunLine Avail Schedule,2023-04-06,2023-05-03,POINT (-116.22452 33.71472)
1,fd015c94eeb7bea2ce7dfa11890a8c01,f88919081c15e52e44adaf0ba48e6dbc,86,Washington at Ave 50,86,SunLine Avail Schedule,2023-04-06,2023-05-03,POINT (-116.29498 33.68504)
2,f22798a6583ead5386230877befd3982,f88919081c15e52e44adaf0ba48e6dbc,531,Jackson at Ave 44,531,SunLine Avail Schedule,2023-04-06,2023-05-03,POINT (-116.21642 33.72905)
3,378315c1ce33f1954e681dfe4057cb47,f88919081c15e52e44adaf0ba48e6dbc,10,Palm Canyon at Via Escuela,10,SunLine Avail Schedule,2023-04-06,2023-05-03,POINT (-116.54797 33.84817)
4,c506d9ffa21d461ec0bbb2b519a5e857,f88919081c15e52e44adaf0ba48e6dbc,539,Hwy 111 at San Pablo,539,SunLine Avail Schedule,2023-04-06,2023-05-03,POINT (-116.38214 33.7212)
...,...,...,...,...,...,...,...,...,...
171489,b2efa0bfa0135bfb7aadfc42fccc5d7a,4a1e6818c0a8b28f0673d5ad3e5bd494,904609,Richmond,904609,Bay Area 511 BART Schedule,2025-07-30,2025-08-08,POINT (-122.35305 37.93676)
171490,d70ac7770902c390e928ba39681c92e8,4a1e6818c0a8b28f0673d5ad3e5bd494,COLS_3,San Leandro Street Entrance / Exit,COLS_3,Bay Area 511 BART Schedule,2025-07-30,2025-08-08,POINT (-122.19729 37.75395)
171491,55d1a99f47275ad6f176e2274ba617bf,4a1e6818c0a8b28f0673d5ad3e5bd494,BAYF_1,East Entrance / Exit,BAYF_1,Bay Area 511 BART Schedule,2025-07-30,2025-08-08,POINT (-122.12647 37.69708)
171492,1c460be15077dd56da568dc6a8b43892,4a1e6818c0a8b28f0673d5ad3e5bd494,903502,Pleasant Hill / Contra Costa Centre,903502,Bay Area 511 BART Schedule,2025-07-30,2025-08-08,POINT (-122.05602 37.92846)
171493,358f11fb9029d336c0dc9b0c72697fd7,4a1e6818c0a8b28f0673d5ad3e5bd494,904402,El Cerrito Plaza,904402,Bay Area 511 BART Schedule,2025-07-30,2025-08-08,POINT (-122.29897 37.9026)